### PR TITLE
Clean Up

### PR DESCRIPTION
**Pull request by ndonkoHenri**
Cleaned up the code and the also the README file. Review and let me please know what you think.

All files seen as "Deleted" here were moved. See the [description](https://github.com/SKbarbon/Flet_StoryBoard/commit/599bf429000446d1325f5c787965940adb095167) of my first commit for more info.

### CODE REVIEW

**Comment by SKbarbon** [comment]
Thanks!
I will preview this soon and gove you the updates!

**Comment by SKbarbon** [comment]
You did great job, thanks

**Comment by ndonkoHenri** [comment]
Sorry, I don't know what distracted me to miss that last `isinstance`. 😝
Please @SKbarbon to avoid repeating such work and avoid time wastage, let's all try to stick to some python principles. You noticed what I changed and cleaned to make more readable, and understandable.

**Summary**

- comments (no more #* or #?): just be more explicit on the comments you write.
- folder names: let's stick to lowercases
- Enums: favor the usage of Enums in published/remote code instead of strings. Meaning, you can feel free to use strings while coding, but when pushing , use Enums.
- no more `from flet import *`
- When an object or function call has many parameters, split them each line by line. 
- etc... 

I hope you checked the comments starting with "# issue" I added in the code. If not, let me know cause we need to discuss about it!

This was just a first push. I will keep on reviewing with time. What's left now is for me to run the program and search for bugs 🐜 at that level.

**Comment by SKbarbon** [comment]
Hey @ndonkoHenri ,
I did search for the `# issue` you did 🙂.

All of them not an issues for me, except:
`# issue: focused_color can't have value "color"`
I did fix it, thanks!

**Pull request merged**
